version: '3.9'
services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  php:
    container_name: php
    depends_on:
      - postgres
    volumes:
      - ../binotify-app/src:/var/www/html/
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: ../binotify-app
      dockerfile: Dockerfile.backend
    ports:
      - 3000:80
  
  soap:
    container_name: soap
    depends_on:
      - mysql
    volumes:
      - ../binotify-soap-service/src:/var/www/html/
    environment:
      DB_HOST: mysql
      DB_PORT: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
    build:
      context: ../binotify-soap-service
      dockerfile: Dockerfile.backend
    ports:
      - 3001:80

volumes:
  postgres:
  mysql: