version: '3.9'
services:
  postgres-php:
    container_name: postgres-php
    build:
      context: ../binotify-app
      dockerfile: Dockerfile.postgres.dev
    volumes:
      - postgres-php:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PHP}
    restart: always
  
  postgres-rest:
    container_name: postgres-rest
    build:
      context: ../binotify-rest-service
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres-rest:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_REST}
    restart: always

  mysql:
    container_name: mysql
    build:
      context: ../binotify-soap-service
      dockerfile: Dockerfile.mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  redis:
    container_name: redis
    image: redis:7.0.5
    volumes:
      - redis:/data
    restart: always

  php:
    container_name: php
    depends_on:
      - postgres-php
    volumes:
      - ../binotify-app/src:/var/www/html/
    environment:
      POSTGRES_HOST: postgres-php
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PHP}
      API_KEY: ${API_KEY_FRONTEND}
    build:
      context: ../binotify-app
      dockerfile: Dockerfile.backend
    ports:
      - 3000:80
  
  soap:
    container_name: soap
    depends_on:
      - mysql
    volumes:
      - ../binotify-soap-service/src:/var/www/html/
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
    build:
      context: ../binotify-soap-service
      dockerfile: Dockerfile.soap
    ports:
      - 3001:80

  rest:
    container_name: rest
    depends_on:
      - postgres-rest
      - redis
    environment:
      POSTGRES_HOST: postgres-rest
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_REST}
      API_KEY: ${API_KEY_REST}
      WAIT_HOSTS: postgres-rest:5432, redis:6379
    build:
      context: ../binotify-rest-service
      dockerfile: Dockerfile.rest
    ports:
      - 3002:80

volumes:
  postgres-php:
  postgres-rest:
  mysql:
  redis: